# Vector Auto-Regressive (VAR) models


@Kilian_1998 See [this page](https://rdrr.io/cran/VAR.etp/man/VAR.Boot.html)

Sign restrictions: [package](https://github.com/chrstdanne/VARsignR), @Danne_2015.

@vars
<!-- toBibtex(citation("vars")) -->

@Stargazer


```{r VARBoot, message=FALSE, warning=FALSE}
library(VAR.etp)
library(vars) #standard VAR models
data(dat) # part of VAR.etp package
a <- VAR.Boot(dat,p=2,nb=200,type="const")
b <- VAR(dat,p=2)
rbind(a$coef[1,],(a$coef+a$Bias)[1,],b$varresult$inv$coefficients)
```


VARs are widely used in macroeconomic analysis. While simple and easy to estimate, they make it possible to conveniently capture the dynamics of complex multivariate systems. VAR popularity is notably due to @Sims_1980's influential work. In economics, VAR models are often employed in order to identify *structural* shocks. First, we will present VAR models. Second, we will study its *structural* extension (SVAR models).

:::{.definition #SVAR name="(S)VAR model"}
Let $y_{t}$ denote a $n \times1$ vector of random variables. Process $y_{t}$ follows a $p^{th}$-order VAR if, for all $t$, we have
\begin{eqnarray}
\begin{array}{rllll}
VAR:& y_t &=& c + \Phi_1 y_{t-1} + \dots + \Phi_p y_{t-p} + \varepsilon_t,& \varepsilon_t:\mbox{ (correlated) innovation}\\
SVAR:& y_t &=& c + \Phi_1 y_{t-1} + \dots + \Phi_p y_{t-p} + B \eta_t,& \eta_t:\mbox{ ($\bot$) structural shock},
\end{array}(\#eq:yVAR)
\end{eqnarray}
with $\varepsilon_t = B\eta_t$. We assume that $\{\eta_{t}\}$ is a white noise sequence whose components are are mutually and serially independent.
:::

The first line of Eq. \@ref(eq:yVAR) corresponds to the **reduced-form** of the VAR model (**structural form** for the second line).

Eq. \@ref(eq:yVAR) can also be written:
$$
y_{t}=c+\Phi(L)y_{t-1}+\varepsilon_{t},
$$
with $\Phi(L) = \Phi_1 + \Phi_2 L + \dots + \Phi_p L^{p-1}$.

Consequently:
$$
y_{t}\mid y_{t-1},y_{t-2},\ldots,y_{-p+1}\sim \mathcal{N}(c+\Phi_{1}y_{t-1}+\ldots\Phi_{p}y_{t-p},\Omega).
$$

Using @Hamilton_1994's notations, denote with $\Pi$ the matrix $\left[\begin{array}{ccccc}
c & \Phi_{1} & \Phi_{2} & \ldots & \Phi_{p}\end{array}\right]'$ and with $x_{t}$ the vector $\left[\begin{array}{ccccc}
1 & y'_{t-1} & y'_{t-2} & \ldots & y'_{t-p}\end{array}\right]'$, we have:
\begin{equation}
y_{t}= \Pi'x_{t} + \varepsilon_{t}. (\#eq:PIVAR)
\end{equation}
The previous representation is convenient to discuss the estimation of the VAR model, as parameters are gathered in two matrices only: $\Pi$ and $\Omega$.

### VAR estimation

Let us start with the case where the shocks are Gaussian.

:::{.proposition #estimVARGaussian name="MLE of a Gaussian VAR"}
If $y_t$ follows a VAR(p) (see Definition \@ref(def:SVAR)), and if $\varepsilon_t \sim \,i.i.d.\,\mathcal{N}(0,\Omega)$, then the ML estimate of $\Pi$, denoted by $\hat{\Pi}$ (see Eq. \@ref(eq:PIVAR)), is given by
\begin{equation}
\hat{\Pi}=\left[\sum_{t=1}^{T}x_{t}x'_{t}\right]^{-1}\left[\sum_{t=1}^{T}y_{t}'x_{t}\right]= (\bv{X}'\bv{X})^{-1}\bv{X}'\bv{y},(\#eq:Pi)
\end{equation}
where $\bv{X}$ is the $T \times (np)$ matrix whose $t^{th}$ row is $x_t$ and where $\bv{y}$ is the $T \times n$ matrix whose $t^{th}$ row is $y_{t}'$.

That is, the $i^{th}$ column of $\hat{\Pi}$ ($b_i$, say) is the OLS estimate of $\beta_i$, where:
\begin{equation}
y_{i,t} = \beta_i'x_t + \varepsilon_{i,t},(\#eq:betayx)
\end{equation}
(i.e., $\beta_i' = [c_i,\phi_{i,1}',\dots,\phi_{i,p}']'$).

The ML estimate of $\Omega$, denoted by $\hat{\Omega}$, coincides with the sample covariance matrix of the $n$ series of the OLS residuals in Eq. \@ref(eq:betayx), i.e.:
\begin{equation}
\hat{\Omega} = \frac{1}{T} \sum_{i=1}^T \hat{\varepsilon}_t\hat{\varepsilon}_t',\quad\mbox{with } \hat{\varepsilon}_t= y_t - \hat{\Pi}'x_t.
\end{equation}

The asymptotic distributions of these estimators are the ones resulting from standard OLS formula.
:::


:::{.proof}
See Appendix \@ref(estimVARGaussian).
:::


As stated by Proposition \@ref(OLSVAR), when the shocks are not Gaussian, then the OLS regressions still provide consistent estimates of the model parameters. However, since $x_t$ correlates to $\varepsilon_s$ for $s<t$, the OLS estimator $\bv{b}_i$ of $\boldsymbol\beta_i$ is biased in small sample. (That is also the case for the ML estimator.)

Indeed, denoting by $\boldsymbol\varepsilon_i$ the $T \times 1$ vector of $\varepsilon_{i,t}$'s, and using the notations of $b_i$ and $\beta_i$ introduced in Proposition \@ref(prp:estimVARGaussian), we have:
\begin{equation}
\bv{b}_i = \beta_i + (\bv{X}'\bv{X})^{-1}\bv{X}'\boldsymbol\varepsilon_i.(\#eq:olsar1)
\end{equation}
We have non-zero correlation between $x_t$ and $\varepsilon_{i,s}$ for $s<t$ and, therefore, $\mathbb{E}[(\bv{X}'\bv{X})^{-1}\bv{X}'\boldsymbol\varepsilon_i] \ne 0$.

However, when $y_t$ is covariance stationary, then $\frac{1}{n}\bv{X}'\bv{X}$ converges to a positive definite matrix $\bv{Q}$, and $\frac{1}{n}X'\boldsymbol\varepsilon_i$ converges to 0. Hence $\bv{b}_i \overset{p}{\rightarrow} \beta_i$. More precisely:

:::{.proposition #OLSVAR name="Asymptotic distribution of the OLS estimate of $\beta_i$"}
If $y_t$ follows a VAR model, as defined in Definition \@ref(def:SVAR), we have:
$$
\sqrt{T}(\bv{b}_i-\beta_i) =  \underbrace{\left[\frac{1}{T}\sum_{t=p}^T x_t x_t' \right]^{-1}}_{\overset{p}{\rightarrow} \bv{Q}^{-1}}
\underbrace{\sqrt{T} \left[\frac{1}{T}\sum_{t=1}^T x_t\varepsilon_{i,t} \right]}_{\overset{d}{\rightarrow} \mathcal{N}(0,\sigma_i^2\bv{Q})},
$$
where $\sigma_i = \mathbb{V}ar(\varepsilon_{i,t})$ and where $\bv{Q} = \mbox{plim }\frac{1}{T}\sum_{t=p}^T x_t x_t'$ is given by:
\begin{equation}
\bv{Q} = \left[
\begin{array}{ccccc}
1 & \mu' &\mu' & \dots & \mu' \\
\mu & \gamma_0 + \mu\mu' & \gamma_1 + \mu\mu' & \dots & \gamma_{p-1} + \mu\mu'\\
\mu & \gamma_1 + \mu\mu' & \gamma_0 + \mu\mu' & \dots & \gamma_{p-2} + \mu\mu'\\
\vdots &\vdots &\vdots &\dots &\vdots \\
\mu & \gamma_{p-1} + \mu\mu' & \gamma_{p-2} + \mu\mu' & \dots & \gamma_{0} + \mu\mu'
\end{array}
\right].(\#eq:Qols)
\end{equation}
:::

:::{.proof}
See Appendix \@ref(OLSVAR).
:::

The following proposition extends the previous proposition and includes covariances between different $\beta_i$'s as well as the asymptotic distribution of the ML estimates of $\Omega$.

:::{.proposition #OLSVAR2 name="Asymptotic distribution of the OLS estimates"}
If $y_t$ follows a VAR model, as defined in Definition \@ref(def:SVAR), we have:
\begin{equation}
\sqrt{T}\left[
\begin{array}{c}
vec(\hat\Pi - \Pi)\\
vec(\hat\Omega - \Omega)
\end{array}
\right]
\sim \mathcal{N}\left(0,
\left[
\begin{array}{cc}
\Omega \otimes \bv{Q}^{-1} & 0\\
0 & \Sigma_{22}
\end{array}
\right]\right),(\#eq:asymptPi)
\end{equation}
where the component of $\Sigma_{22}$ corresponding to the covariance between $\hat\sigma_{i,j}$ and $\hat\sigma_{k,l}$ (for $i,j,l,m \in \{1,\dots,n\}^4$) is equal to $\sigma_{i,l}\sigma_{j,m}+\sigma_{i,m}\sigma_{j,l}$.
:::

:::{.proof}
See @Hamilton_1994, Appendix of Chapter 11.
:::

Naturally, in practice, $\Omega$ is replaced by $\hat{\Omega}$, $Q$ is replaced with $\hat{\bv{Q}} = \frac{1}{T}\sum_{t=p}^T x_t x_t'$ and $\Sigma$ with the matrix whose components are of the form $\hat\sigma_{i,l}\hat\sigma_{j,m}+\hat\sigma_{i,m}\hat\sigma_{j,l}$, where the $\hat\sigma_{i,l}$'s are the components of $\hat\Omega$.


The simplicity of the VAR framework and the tractability of its MLE open the way to convenient econometric testing. Let's illustrate this with the likelihood ratio test. The maximum value achieved by the MLE is
$$
\log\mathcal{L}(Y_{T};\hat{\Pi},\hat{\Omega}) = -\frac{Tn}{2}\log(2\pi)+\frac{T}{2}\log\left|\hat{\Omega}^{-1}\right| -\frac{1}{2}\sum_{t=1}^{T}\left[\hat{\varepsilon}_{t}'\hat{\Omega}^{-1}\hat{\varepsilon}_{t}\right].
$$
The last term is:
\begin{eqnarray*}
\sum_{t=1}^{T}\hat{\varepsilon}_{t}'\hat{\Omega}^{-1}\hat{\varepsilon}_{t} &=& \mbox{Tr}\left[\sum_{t=1}^{T}\hat{\varepsilon}_{t}'\hat{\Omega}^{-1}\hat{\varepsilon}_{t}\right] = \mbox{Tr}\left[\sum_{t=1}^{T}\hat{\Omega}^{-1}\hat{\varepsilon}_{t}\hat{\varepsilon}_{t}'\right]\\
&=&\mbox{Tr}\left[\hat{\Omega}^{-1}\sum_{t=1}^{T}\hat{\varepsilon}_{t}\hat{\varepsilon}_{t}'\right] = \mbox{Tr}\left[\hat{\Omega}^{-1}\left(T\hat{\Omega}\right)\right]=Tn.
\end{eqnarray*}
Therefore, the optimized log-likelihood is simply obtained by:
\begin{equation}
\log\mathcal{L}(Y_{T};\hat{\Pi},\hat{\Omega})=-(Tn/2)\log(2\pi)+(T/2)\log\left|\hat{\Omega}^{-1}\right|-Tn/2.(\#eq:optimzedLogL)
\end{equation}

Assume that we want to test the null hypothesis that a set of variables follows a VAR($p_{0}$) against the alternative
specification of $p_{1}$ ($>p_{0}$).

Let us denote by $\hat{L}_{0}$ and $\hat{L}_{1}$ the maximum log-likelihoods obtained with $p_{0}$ and $p_{1}$ lags, respectively.

Under the null hypothesis ($H_0$: $p=p_0$), we have:
\begin{eqnarray*}
2\left(\hat{L}_{1}-\hat{L}_{0}\right)&=&T\left(\log\left|\hat{\Omega}_{1}^{-1}\right|-\log\left|\hat{\Omega}_{0}^{-1}\right|\right)  \sim \chi^2(n^{2}(p_{1}-p_{0})).
\end{eqnarray*}


**Block exogeneity**

Let's decompose $y_t$ into two subvectors $y^{(1)}_{t}$ ($n_1 \times 1$) and $y^{(2)}_{t}$ ($n_2 \times 1$), with $y_t' = [{y^{(1)}_{t}}',{y^{(2)}_{t}}']$ (and therefore $n=n_1 +n_2$), such that:
$$
\left[
\begin{array}{c}
y^{(1)}_{t}\\
y^{(2)}_{t}
\end{array}
\right] = \left[
\begin{array}{cc}
\Phi^{(1,1)} & \Phi^{(1,2)}\\
\Phi^{(2,1)} & \Phi^{(2,2)}
\end{array}
\right]
\left[
\begin{array}{c}
y^{(1)}_{t-1}\\
y^{(2)}_{t-1}
\end{array}
\right] + \varepsilon_t.
$$
One can easily test for block exogeneity of $y_t^{(2)}$ (say). The null assumption ca n be expressed as $\Phi^{(2,1)}=0$ and $\Sigma^{(2,1)}=0$.

**Lag selection**

In a VAR, adding lags consumes numerous degrees of freedom: with $p$ lags, each of the $n$ equations in the VAR contains $n\times p$ coefficients plus the intercept term.

Adding lags improve in-sample fit, but is likely to result in over-parameterization and affect the {\color{blue}out-of-sample} prediction performance.

To select appropriate lag length, so-called **selection criteria** can be used (see Definition \@ref(def:infocriteria)). These criteria have to be minimized. That is, the best specification is the one giving the lowest criteria.

In the context of VAR models, using Eq. \@ref(eq:optimzedLogL), we have:
\begin{eqnarray*}
AIC & = & cst + \log\left|\hat{\Omega}\right|+\frac{2}{T}N\\
BIC & = & cst + \log\left|\hat{\Omega}\right|+\frac{\log T}{T}N,
\end{eqnarray*}
where $N=p \times n^{2}$.

**Companion Form and Stability of a VAR process**

Let us introduce vector $y_{t}^{*}$, whihc stacks the last $p$ values of $y_t$:
$$
y_{t}^{*}=\left[\begin{array}{cccc}
y'_{t} & y'_{t-1} & \ldots & y'_{t-p+1}\end{array}\right]^{'},
$$
Eq. \@ref(eq:yVAR) can then be rewritten in its companion form:
\begin{equation}
y_{t}^{*} =
\underbrace{\left[\begin{array}{c}
c\\
0\\
\vdots\\
0\end{array}\right]}_{=c^*}+
\underbrace{\left[\begin{array}{cccc}
\Phi_{1} & \Phi_{2} & \cdots & \Phi_{p}\\
I & 0 & \cdots & 0\\
0 & \ddots & 0 & 0\\
0 & 0 & I & 0\end{array}\right]}_{=\Phi}
y_{t-1}^{*}+
\underbrace{\left[\begin{array}{c}
\varepsilon_{t}\\
0\\
\vdots\\
0\end{array}\right]}_{\varepsilon_t^*}(\#eq:ystarVAR)
\end{equation}

Matrices $\Phi$ and $\Sigma^* = \mathbb{V}ar(\varepsilon_t^*)$ are of dimension $np \times np$. $\Sigma^*$ is filled with zeros, except the $n\times n$ upper-left block that is equal to $\Sigma = \mathbb{V}ar(\varepsilon_t)$.

We then have:
\begin{eqnarray*}
y_{t}^{*} & = & c^{*}+\Phi\left(c^{*}+\Phi y_{t-2}^{*}+\varepsilon_{t-1}^{*}\right)+\varepsilon_{t}^{*} \nonumber \\
& = & c^{*}+\varepsilon_{t}^{*}+\Phi(c^{*}+\varepsilon_{t-1}^{*})+\ldots+\Phi^{k}(c^{*}+\varepsilon_{t-k}^{*})+\Phi^k y_{t-k}^{*}.
\end{eqnarray*}

If the eigenvalues of $\Phi$ are strictly within the unit circle, then $\Phi^k$ geometrically decays to the zero matrix and we get the following Wold decomposition for $y_t$:
\begin{eqnarray}
y_{t}^{*}  & = & c^{*}+\varepsilon_{t}^{*}+\Phi(c^{*}+\varepsilon_{t-1}^{*})+\ldots+\Phi^{k}(c^{*}+\varepsilon_{t-k}^{*})+\ldots \nonumber \\
& = & \mu^{*} +\varepsilon_{t}^{*}+\Phi\varepsilon_{t-1}^{*}+\ldots+\Phi^{k}\varepsilon_{t-k}^{*}+\ldots,(\#eq:VARstar)
\end{eqnarray}
where $\mu^* = (I - \Phi)^{-1} c^*$.

(It can also be seen that $\mu^{*} = [\mu',\dots,\mu']'$, where $\mu = (I - \Phi_1 - \dots - \Phi_p)^{-1}c$).

The unconditional variance of $y_t$ can be derived from Eq. \@ref(eq:VARstar), exploiting the fact that the $\varepsilon_{t}^{*}$ are serially uncorrelated:
$$
\mathbb{V}ar(y_t^*)=\Omega^*+\Phi\Omega^*\Phi'+\ldots+\Phi^{k}\Omega^*\Phi'^{k}+\ldots,
$$
with $\mathbb{V}ar(\varepsilon_t^*)=\Omega^*$.

The unconditional variance of $y_t$ is the upper-left $n\times n$ block of matrix $\mathbb{V}ar(y_t^*)$.

Eq. \@ref(eq:VARstar) also implies that the $\Psi_k$ matrices defining the IRFs  (see Eq. \@ref(eq:InfMA)) are given by: $\Psi_k = \widetilde{\Phi^k}B$, where $\widetilde{\Phi^k}$ is the upper-left matrix block of $\Phi^k$.

**Granger Causality**

@Granger_1969 developed a method to explore **causal relationships** among variables. The approach consists in determining whether the past values of $y_{1,t}$ can help explain the current $y_{2,t}$ (beyond the information already included in the past values of $y_{2,t}$).

Formally, let us denote three information sets:
\begin{eqnarray*}
\mathcal{I}_{1,t} & = & \left\{ y_{1,t},y_{1,t-1},\ldots\right\} \\
\mathcal{I}_{2,t} & = & \left\{ y_{2,t},y_{2,t-1},\ldots\right\} \\
\mathcal{I}_{t} & = & \left\{ y_{1,t},y_{1,t-1},\ldots y_{2,t},y_{2,t-1},\ldots\right\}.
\end{eqnarray*}
We say that $y_{1,t}$ Granger-causes $y_{2,t}$ if
$$
\mathbb{E}\left[y_{2,t}\mid \mathcal{I}_{2,t-1}\right]\neq \mathbb{E}\left[y_{2,t}\mid \mathcal{I}_{t-1}\right].
$$

To get the intuition behind the testing procedure, consider the following
bivariate VAR($p$) process:
\begin{eqnarray*}
y_{1,t} & = & c_1+\Sigma_{i=1}^{p}\Phi_i^{(11)}y_{1,t-i}+\Sigma_{i=1}^{p}\Phi_i^{(12)}y_{2,t-i}+\varepsilon_{1,t}\\
y_{2,t} & = & c_2+\Sigma_{i=1}^{p}\Phi_i^{(21)}y_{1,t-i}+\Sigma_{i=1}^{p}\Phi_i^{(22)}y_{2,t-i}+\varepsilon_{2,t},
\end{eqnarray*}
where $\Phi_k^{(ij)}$ denotes the element $(i,j)$ of $\Phi_k$.

Then, $y_{1,t}$ is said not to Granger-cause $y_{2,t}$ if
$$
\Phi_1^{(21)}=\Phi_2^{(21)}=\ldots=\Phi_p^{(21)}=0.
$$
Therefore the hypothesis testing is
$$
\begin{cases}
H_{0}: & \Phi_1^{(21)}=\Phi_2^{(21)}=\ldots=\Phi_p^{(21)}=0\\
H_{1}: & \Phi_1^{(21)}\neq0\mbox{ or }\Phi_2^{(21)}\neq0\mbox{ or}\ldots\Phi_p^{(21)}\neq0.\end{cases}
$$
Loosely speaking, we reject $H_{0}$ if some of the coefficients on the lagged $y_{1,t}$'s are statistically significant. Formally, this can be tested using the $F$-test or asymptotic chi-square test. The $F$-statistic is
$$
F=\frac{(RSS-USS)/p}{USS/(T-2p-1)},
$$
where RSS is the Restricted sum of squared residuals and USS is the Unrestricted sum of squared residuals. Under $H_{0}$, the $F$-statistic is distributed as $\mathcal{F}(p,T-2p-1)$.

Note that $pF\underset{T \rightarrow \infty}{\rightarrow}\chi^{2}(p)$. Therefore, for large samples and under $H_0$:
$$
F \sim \chi^{2}(p)/p.
$$

**Factor-Augmented VAR (FAVAR)**

VAR models are subject to the curse of dimensionality: If $n$, is large, then the number of parameters (in $n^2$) explodes.

In the case where one suspects that the $y_{i,t}$'s are mainly driven by a small number of random sources, a **factor structure** may be imposed (@Bernanke_Boivin_Eliasz_2005).

Let us denote by $f_t$ a $k$-dimensional vector of latent factors accounting for important shares of the variances of the $y_{i,t}$'s (with $k \ll n$) and by $x_t$ is a small $q$-dimensional subset of $y_t$ (with $q \ll n$). The following factor structure is posited:
$$
y_t = \Lambda^f f_t + \Lambda^x x_t + e_t,
$$
where the $e_t$ are ``small'' serially and mutually i.i.d. error terms.

The model is complemented by positing a VAR dynamics for $[f_t',x_t']'$:
\begin{equation}
\left[\begin{array}{c}f_t\\x_t\end{array}\right] = \Phi(L)\left[\begin{array}{c}f_{t-1}\\x_{t-1}\end{array}\right] + v_t.(\#eq:FAVAR)
\end{equation}

$f_t$ e.g. $\equiv$ the first $k$ principal components of $y_t$.

Standard identification techniques of structural shocks can be employed in Eq. \@ref(eq:FAVAR): Cholesky approach can be used for instance if the last component of $x_t$ is the short-term interest rate and if it is assumed that a MP shock has no contemporaneous impact on other macro-variables (in $y_t$).


## Identification Problem and Standard Identification Techniques

**The Identification Issue***

In the previous section, we have seen how to estimate $\Omega$ and the $\Phi_k$ matrices in the context of a VAR model. But the IRFs are functions of $B$ and the $\Phi_k$'s, not of $\Omega$ the $\Phi_k$'s. We have $\Omega = BB'$, but this is not sufficient to recover $B$.

Indeed, seen a system of equations whose unknowns are the $b_{i,j}$'s (components of $B$), the system  $\Omega = BB'$ contains only $n(n+1)/2$ linearly independent equations. Example for $n=2$:
\begin{eqnarray*}
&&\left[
\begin{array}{cc}
\omega_{11} & \omega_{12} \\
\omega_{12} & \omega_{22}
\end{array}
\right] = \left[
\begin{array}{cc}
b_{11} & b_{12} \\
b_{21} & b_{22}
\end{array}
\right]\left[
\begin{array}{cc}
b_{11} & b_{21} \\
b_{12} & b_{22}
\end{array}
\right]\\
&\Leftrightarrow&\left[
\begin{array}{cc}
\omega_{11} & \omega_{12} \\
\omega_{12} & \omega_{22}
\end{array}
\right] = \left[
\begin{array}{cc}
b_{11}^2+b_{12}^2 & {\color{red}b_{11}b_{21}+b_{12}b_{22}} \\
{\color{red}b_{11}b_{21}+b_{12}b_{22}} & b_{22}^2 + b_{21}^2
\end{array}
\right].
\end{eqnarray*}

We have 3 linearly independent equations but 4 unknowns. Therefore, $B$ is not identified based on second-order moments. Additional restrictions are required to identify $B$.

This section covers two standard identification schemes: **short-run** and **long-run** restrictions:

1. a **short-run restriction (SRR)** prevents a structural shock from affecting an endogenous variable contemporaneously.
* Easy to implement: the appropriate entries of $B$ are set to 0.
* Particular case: **Cholesky, or recursive approach**.
* Examples: @BERNANKE198649, @Sims_1986, @Gali_1992, @RubioRamirez_et_al_2010.

2. a **long-run restriction (LRR)** prevents a structural shock from having a cumulative impact on one of the endogenous variables. 
* Additional computations are required to implement this. One needs to compute the cumulative effect of one of the structural shocks $u_{t}$ on one of the endogenous variable.
* Examples: @Blanchard_Quah_1989, @Faust_Leeper_1997, @Gali_1999, @Erceg_et_al_2005, @NBERc11177.

The two approaches can be combined (see, e.g., @Gerlach_Smets_1995).

**A Simple Example**

Consider the following stylized economic dynamics:
\begin{equation}
\begin{array}{clll}
g_{t}&=& \bar{g}-\lambda(i_{t-1}-\mathbb{E}_{t-1}\pi_{t})+ \underbrace{{\color{blue}\sigma_d \eta_{d,t}}}_{\mbox{demand shock}}& (\mbox{IS curve})\\
\Delta \pi_{t} & = & \beta (g_{t} - \bar{g})+ \underbrace{{\color{blue}\sigma_{\pi} \eta_{\pi,t}}}_{\mbox{cost push shock}} & (\mbox{Phillips curve})\\
i_{t} & = & \rho i_{t-1} + \left[ \gamma_\pi \mathbb{E}_{t}\pi_{t+1}  + \gamma_g (g_{t} - \bar{g}) \right]\\
&& \qquad \qquad+\underbrace{{\color{blue}\sigma_{mp} \eta_{mp,t}}}_{\mbox{Mon. Pol. shock}} & (\mbox{Taylor rule}),
\end{array}(\#eq:systemI)
\end{equation}
where:
\begin{equation}
\eta_t = 
\left[
\begin{array}{c}
\eta_{\pi,t}\\
\eta_{d,t}\\
\eta_{mp,t}
\end{array}
\right]
\sim i.i.d.\,\mathcal{N}(0,I).(\#eq:covU)
\end{equation}

Vector $\eta_t$ is a vector of Gaussian {\color{blue}structural shocks}, mutually and serially independent.

On date $t$:

* $g_t$ is contemporaneously affected by $\eta_{d,t}$ only;
* $\pi_t$ is contemporaneously affected by $\eta_{\pi,t}$ and $\eta_{d,t}$;
* $i_t$ is contemporaneously affected by $\eta_{mp,t}$, $\eta_{\pi,t}$ and $\eta_{d,t}$.

System \@ref(eq:systemI) could be rewritten in the form:
\begin{equation}
\left[\begin{array}{c}
d_t\\
\pi_t\\
i_t
\end{array}\right]
= \Phi(L)
\left[\begin{array}{c}
d_{t-1}\\
\pi_{t-1}\\
i_{t-1} +
\end{array}\right] +\underbrace{\underbrace{
\left[
\begin{array}{ccc}
0 & \bullet & 0 \\
\bullet & \bullet & 0 \\
\bullet & \bullet & \bullet
\end{array}
\right]}_{=B} \eta_t}_{=\varepsilon_t}(\#eq:BBBB)
\end{equation}

This is the **reduced-form** of the model. This representation suggests three additional restrictions on the entries of $B$; the latter matrix is therefore identified (up to the signs of its columns) as soon as $\Omega = BB'$ is known.

There are particular cases in which some well-known matrix decompositions of $\mathbb{V}ar(\varepsilon_t)=\Omega_\varepsilon$ can be used to easily estimate some specific SVAR.

Consider the following context:

* A first shock (say, $\eta_{n_1,t}$) can affect instantaneously
(i.e., on date $t$) only one of the endogenous variable (say, $y_{n_1,t}$);
* A second shock (say, $\eta_{n_2,t}$) can affect instantaneously
(i.e., on date $t$) the first two endogenous variables (say, $y_{n_1,t}$
and $y_{n_2,t}$);
* ...

This implies (1) that column $n_1$ of $B$ has only 1 non-zero entry (this is the $n_1^{th}$ entry), (2) that column $n_2$ of $B$ has 2 non-zero entries (the $n_1^{th}$ and the $n_2^{th}$ ones), ...

Without loss of generality, we can set $n_1=n$, $n_2=n-1$, ... In this context, matrix $B$ is lower triangular.

The Cholesky decomposition of $\Omega_{\varepsilon}$ then provides an appropriate estimate of $B$, that is a lower triangular matrix $B$ that is such that:
$$
\Omega_\varepsilon = BB'.
$$

For instance, @DEDOLA20051543 estimate 5 structural VAR models for the US, the UK, Germany, France and Italy to analyse the monetary-policy transmission mechanisms. They estimate SVAR(5) models over the period 1975-1997. The shock-identification scheme is based on Cholesky decompositions, the ordering of the endogenous variables being: the industrial production, the consumer price index, a commodity price index, the short-term rate, monetary aggregate and the effective exchange rate (except for the US). This ordering implies that monetary policy reacts to the shocks affecting
the first three variables but that the latter react to monetary policy shocks with a one-period lag.

Importantly, the Cholesky approach can be useful if you are essentially interested in one structural shock. This was the case, e.g., of @Christiano_Eichenbaum_Evans_1996. Their identification is based on the following relationship between $\varepsilon_t$ and $\eta_t$:
$$
\left[\begin{array}{c}
\boldsymbol\varepsilon_{S,t}\\
\varepsilon_{r,t}\\
\boldsymbol\varepsilon_{F,t}
\end{array}\right] =
\left[\begin{array}{ccc}
B_{SS} & 0 & 0 \\
B_{rS} & B_{rr} & 0 \\
B_{FS} & B_{Fr} & B_{FF}
\end{array}\right]
\left[\begin{array}{c}
\boldsymbol\eta_{S,t}\\
\eta_{r,t}\\
\boldsymbol\eta_{F,t}
\end{array}\right],
$$
where $S$, $r$ and $F$ respectively correspond to *slow-moving variables*, the policy variable (short-term rate) and *fast-moving variables*. While $\eta_{r,t}$ is scalar, $\boldsymbol\eta_{S,t}$ and $\boldsymbol\eta_{F,t}$ may be vectors. The space spanned by $\boldsymbol\varepsilon_{S,t}$ is the same as that spanned by $\boldsymbol\eta_{S,t}$. As a result, because $\varepsilon_{r,t}$ is a linear combination of $\eta_{r,t}$ and $\boldsymbol\eta_{S,t}$ (which are $\perp$), it comes that the $B_{rr}\eta_{r,t}$'s are the (population) residuals in the regression of $\varepsilon_{r,t}$ on $\boldsymbol\varepsilon_{S,t}$. Because $\mathbb{V}ar(\eta_{r,t})=1$, $B_{rr}$ is given by the square root of the variance of  $B_{rr}\eta_{r,t}$. $B_{F,r}$ is finally obtained by regressing the components of $\boldsymbol\varepsilon_{F,t}$ on $\eta_{r,t}$.

An equivalent approach consists in computing the Cholesky decomposition of $BB'$ and keep only the column corresponding to the policy variable.

**Long-run restrictions**

A second type of restriction relates to the long-run influence of a shock on an endogenous variable. Let us consider for instance a structural shock that is assumed to have no "long-run influence" on GDP. How to express this? The long-run change in GDP can be expressed as $GDP_{t+h} - GDP_t$, with $h$ large. Note further that:
$$
GDP_{t+h} - GDP_t = \Delta GDP_{t+h} +\Delta GDP_{t+h-1} + \dots + \Delta GDP_{t+1}.
$$
Hence, the fact that a given structural shock ($\eta_{i,t}$, say) has no long-run influence on GDP means that
$$
\lim_{h\rightarrow\infty}\frac{\partial GDP_{t+h}}{\partial \eta_{i,t}} = \lim_{h\rightarrow\infty} \frac{\partial}{\partial \eta_{i,t}}\left(\sum_{k=1}^h \Delta  GDP_{t+k}\right)= 0.
$$

This can be easily formulated as a function of $B$ when $y_t$ (including $\Delta GDP_t$) follows a VAR(MA) process.

As was shown previously (Eq. \@ref(eq:ystarVAR)), one can always write a VAR($p$) as a VAR(1). Consequently, let us focus on the VAR(1) case:
\begin{eqnarray}
y_{t} &=& c+\Phi y_{t-1}+\varepsilon_{t}\\
& = & c+\varepsilon_{t}+\Phi(c+\varepsilon_{t-1})+\ldots+\Phi^{k}(c+\varepsilon_{t-k})+\ldots \nonumber \\
& = & \mu +\varepsilon_{t}+\Phi\varepsilon_{t-1}+\ldots+\Phi^{k}\varepsilon_{t-k}+\ldots \\
& = & \mu +B\eta_{t}+\Phi B\eta_{t-1}+\ldots+\Phi^{k}B\eta_{t-k}+\ldots,
\end{eqnarray}

The sequence of shocks $\{\eta_t\}$ determines the sequence $\{y_t\}$. What if $\{\eta_t\}$ is replaced by $\{\tilde{\eta}_t\}$, where $\tilde{\eta}_t=\eta_t$ if $t \ne s$ and $\tilde{\eta}_s=\eta_s + \gamma$?

Assume $\{\tilde{y}_t\}$ is the associated "perturbated" sequence. We have $\tilde{y}_t = y_t$ if $t<s$. For $t \ge s$, the Wold decomposition of $\{\tilde{y}_t\}$ implies:
$$
\tilde{y}_t = y_t + \Phi^{t-s} B \gamma.
$$

Therefore, the cumulative impact of $\gamma$ on $\tilde{y}_t$ will be (for $t \ge s$):
\begin{eqnarray}
(\tilde{y}_t - y_t) +  (\tilde{y}_{t-1} - y_{t-1}) + \dots +  (\tilde{y}_s - y_s) &=& \nonumber \\
(Id + \Phi + \Phi^2 + \dots + \Phi^{t-s}) B \gamma.&& (\#eq:cumul)
\end{eqnarray}

Consider a shock on $\eta_{1,t}$, with a magnitude of $1$. This shock is $\gamma = [1,0,\dots,0]'$. Given Eq. \@ref{eq:cumul), the long-run cumulative effect of this shock on the endogenous variables is given by:
$$
(Id+\Phi+\ldots+\Phi^{k}+\ldots)B\left[\begin{array}{c}
1\\
0\\
\vdots\\
0\end{array}\right],
$$
that is the first column of $\Theta \equiv (I+\Phi+\ldots+\Phi^{k}+\ldots)B$.

In this context, consider the following long-run restriction: *"$j^{th}$ structural shock has no cumulative impact on the $i^{th}$ endogenous variable"* is equivalent to
$$
\Theta_{ij}=0,
$$
where $\Theta_{ij}$ is the element $(i,j)$ of $\Theta$.

@Blanchard_Quah_1989 implement long-run restrictions in a small-scale VAR. Two variables are considered: GDP and unemployment. Consequently, the VAR is affected by two types of shocks. The authors want to identify **supply shocks** (that can have a permanent effect on output) and **demand shocks** (that cannot have a permanent effect on output).

The motivation of the authors regarding their long-run restrictions can be obtained from a traditional Keynesian view of fluctuations. The authors propose a variant of a model from @Fischer_1977:
\begin{eqnarray}
Y_{t} & = & M_{t}-P_{t}+a.\theta_{t}(\#eq:demand)\\
Y_{t} & = & N_{t}+\theta_{t}(\#eq:prodfunct)\\
P_{t} & = & W_{t}-\theta_{t}(\#eq:PS)\\
W_{t} & = & W\mid\left\{ \mathbb{E}_{t-1}N_{t}=\overline{N}\right\}. (\#eq:WS)
\end{eqnarray}
To close the model, the authors assume the following dynamics for the money supply and the productivity:
\begin{eqnarray*}
M_{t} & = & M_{t-1}+\varepsilon_{t}^{d}\\
\theta_{t} & = & \theta_{t-1}+\varepsilon_{t}^{s}.
\end{eqnarray*}
In this context, it can be shown that
\begin{eqnarray*}
\Delta Y_{t} & = & (\varepsilon_{t}^{d}-\varepsilon_{t-1}^{d})+a.(\varepsilon_{t}^{s}-\varepsilon_{t-1}^{s})+\varepsilon_{t}^{s}\\
u_{t} & = & -\varepsilon_{t}^{d}-a\varepsilon_{t}^{s}
\end{eqnarray*}
Then, it appears that the demand shocks have no long-run cumulative impact on $\Delta Y_{t}$, the GDP growth, i.e. no long-term impact on output $Y_t$. The vector of endogenous variables is $y_t = [\Delta Y_{t} \quad u_{t}]'$ where $\Delta Y_{t}$ denotes the GDP growth. Estimation data are quarterly, and span the period from 1950:2 to 1987:4; 8 lags are used in the VAR model.
